apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-e8vi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-e8vi
    app.kubernetes.io/part-of: integ-app-mqmz
  name: hacbs-test-project-e8vi
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-e8vi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-e8vi
    spec:
      containers:
      - image: quay.io/kasem_org/integration3-kitf-tenant/integ-app-mqmz/hacbs-test-project-e8vi@sha256:6afb73cf0bbba61d1d26caa76a5e06ac84ace65a6aadabe05331e4b14c7aca27
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
